<?php
/**
 * Rolling Reno v2 — single.php
 * Editorial post template — no sidebar, full-width
 * Spec: post-template-v2.md
 */

get_header();
?>

<main id="main" role="main">
<?php
while ( have_posts() ) :
    the_post();
    $post_id   = get_the_ID();
    $hero_img  = rr_get_post_image_url( $post_id, 'rr-hero' );
    $hero_img_caption = get_post_meta( $post_id, '_rr_hero_caption', true );
?>

<article <?php post_class( 'post-single' ); ?> aria-labelledby="post-title-<?php echo $post_id; ?>">

    <!-- Breadcrumb -->
    <div class="container--narrow">
        <?php rr_breadcrumb(); ?>
    </div>

    <!-- Post Header -->
    <header class="post-header container--narrow">
        <div class="post-header__badge">
            <?php echo rr_category_badge( $post_id ); ?>
        </div>

        <h1 class="post-header__title" id="post-title-<?php echo $post_id; ?>">
            <?php the_title(); ?>
        </h1>

        <div class="post-header__meta">
            <?php
            $avatar = get_theme_mod( 'rr_mara_avatar', '' );
            if ( $avatar ) : ?>
                <img
                    class="post-header__avatar"
                    src="<?php echo esc_url( $avatar ); ?>"
                    alt=""
                    width="36"
                    height="36"
                    loading="lazy"
                    aria-hidden="true"
                >
            <?php endif; ?>

            <a href="<?php echo esc_url( home_url( '/about' ) ); ?>" class="post-header__author">
                Mara Collins
            </a>
            <span class="post-header__meta-dot" aria-hidden="true">·</span>
            <time class="post-header__date" datetime="<?php echo esc_attr( get_the_date( 'Y-m-d' ) ); ?>">
                <?php echo get_the_date(); ?>
            </time>
            <span class="post-header__meta-dot" aria-hidden="true">·</span>
            <span class="post-header__read-time"><?php echo esc_html( rr_read_time( $post_id ) ); ?></span>

            <!-- Share buttons -->
            <div class="post-header__share" aria-label="<?php esc_attr_e( 'Share this post', 'rolling-reno' ); ?>">
                <a
                    href="https://twitter.com/intent/tweet?url=<?php echo urlencode( get_permalink() ); ?>&text=<?php echo urlencode( get_the_title() ); ?>"
                    class="post-header__share-btn"
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label="<?php esc_attr_e( 'Share on Twitter', 'rolling-reno' ); ?>"
                >𝕏</a>
                <a
                    href="https://pinterest.com/pin/create/button/?url=<?php echo urlencode( get_permalink() ); ?>&description=<?php echo urlencode( get_the_title() ); ?>"
                    class="post-header__share-btn"
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label="<?php esc_attr_e( 'Save to Pinterest', 'rolling-reno' ); ?>"
                >📌</a>
                <a
                    href="mailto:?subject=<?php echo urlencode( get_the_title() ); ?>&body=<?php echo urlencode( get_permalink() ); ?>"
                    class="post-header__share-btn"
                    aria-label="<?php esc_attr_e( 'Share via email', 'rolling-reno' ); ?>"
                >✉️</a>
            </div>
        </div>
    </header>

    <!-- Trust / disclosure panel -->
    <div class="container--narrow">
        <?php echo rr_render_post_trust_panel( $post_id ); ?>
    </div>

    <!-- Hero Image (full-bleed) -->
    <div class="post-hero container">
        <?php if ( $hero_img ) : ?>
            <img
                class="post-hero__image"
                src="<?php echo esc_url( $hero_img ); ?>"
                alt="<?php the_title_attribute(); ?>"
                width="1240"
                height="698"
                loading="eager"
                fetchpriority="high"
            >
        <?php else : ?>
            <div class="post-hero__placeholder" aria-hidden="true">🚐</div>
        <?php endif; ?>
        <?php if ( $hero_img_caption ) : ?>
            <p class="post-hero__caption"><?php echo esc_html( $hero_img_caption ); ?></p>
        <?php elseif ( $hero_img && get_post( get_post_thumbnail_id( $post_id ) ) ) :
            $attachment = get_post( get_post_thumbnail_id( $post_id ) );
            if ( $attachment && $attachment->post_excerpt ) : ?>
                <p class="post-hero__caption"><?php echo esc_html( $attachment->post_excerpt ); ?></p>
            <?php endif;
        endif; ?>
    </div>

    <!-- Article Body -->
    <div class="post-body">

        <!-- Table of Contents (auto-generated by JS from H2s) -->
        <?php $headings_count = substr_count( get_the_content(), '<h2' ); ?>
        <?php if ( $headings_count >= 4 ) : ?>
        <nav class="toc" aria-label="<?php esc_attr_e( 'Table of contents', 'rolling-reno' ); ?>" data-collapsed="false">
            <button class="toc__toggle" aria-expanded="true" aria-controls="toc-list-<?php echo $post_id; ?>" type="button">
                <span class="toc__title"><?php esc_html_e( 'In this guide', 'rolling-reno' ); ?></span>
                <span class="toc__chevron" aria-hidden="true">▾</span>
            </button>
            <ol class="toc__list" id="toc-list-<?php echo $post_id; ?>">
                <!-- JS populates this from H2s in .post-body -->
            </ol>
        </nav>
        <?php endif; ?>

        <!-- Post Content -->
        <?php the_content(); ?>

        <!-- Sources / proof note -->
        <?php echo rr_render_post_sources_panel( $post_id ); ?>

        <!-- Mid-post email opt-in (WP filter inserts after content midpoint) -->
        <aside class="mid-post-optin" aria-label="<?php esc_attr_e( 'Newsletter signup', 'rolling-reno' ); ?>">
            <div class="mid-post-optin__inner">
                <div class="mid-post-optin__text">
                    <p class="mid-post-optin__headline">
                        <?php esc_html_e( 'Enjoying this guide?', 'rolling-reno' ); ?>
                    </p>
                    <p class="mid-post-optin__sub">
                        <?php esc_html_e( "Get Mara's free Van Build Starter Kit — the checklist she wishes she'd had on Build #1.", 'rolling-reno' ); ?>
                    </p>
                </div>
                <form class="mid-post-optin__form" action="<?php echo rr_newsletter_action(); ?>" method="POST">
                    <?php wp_nonce_field( 'rr_newsletter', 'rr_nonce' ); ?>
                    <?php rr_newsletter_hidden_fields( 'mid_post_optin' ); ?>
                    <input
                        type="email"
                        name="email"
                        placeholder="<?php esc_attr_e( 'Your email', 'rolling-reno' ); ?>"
                        required
                        aria-label="<?php esc_attr_e( 'Email address', 'rolling-reno' ); ?>"
                        class="mid-post-optin__input"
                    >
                    <button type="submit" class="btn btn--primary btn--sm">
                        <?php esc_html_e( 'Get it free →', 'rolling-reno' ); ?>
                    </button>
                </form>
            </div>
        </aside>

    </div><!-- /.post-body -->

    <!-- Affiliate Products -->
    <div class="container--narrow">
        <?php echo rr_render_affiliate_products( $post_id ); ?>
    </div>

    <!-- Author Bio -->
    <div class="container--narrow">
        <?php get_template_part( 'template-parts/author-bio' ); ?>
    </div>

    <!-- Related Posts -->
    <?php
    $cats = get_the_category( $post_id );
    $related_args = array(
        'posts_per_page'      => 3,
        'post__not_in'        => array( $post_id ),
        'ignore_sticky_posts' => 1,
    );
    if ( $cats ) {
        $related_args['category__in'] = array( $cats[0]->term_id );
    }
    $related_query = new WP_Query( $related_args );
    ?>

    <?php if ( $related_query->have_posts() ) : ?>
    <section class="related-posts" aria-label="<?php esc_attr_e( 'You might also like', 'rolling-reno' ); ?>">
        <h2 class="related-posts__title"><?php esc_html_e( 'You might also like', 'rolling-reno' ); ?></h2>
        <div class="related-posts__grid">
            <?php
            while ( $related_query->have_posts() ) :
                $related_query->the_post();
                $r_thumb = rr_get_post_image_url( get_the_ID(), 'rr-card-sm' );
            ?>
            <article class="post-card" aria-labelledby="related-<?php the_ID(); ?>">
                <a href="<?php the_permalink(); ?>" class="post-card__image-link" tabindex="-1" aria-hidden="true">
                    <div class="post-card__image-wrap">
                        <?php if ( $r_thumb ) : ?>
                            <img class="post-card__image" src="<?php echo esc_url( $r_thumb ); ?>" alt="" width="480" height="360" loading="lazy">
                        <?php else : ?>
                            <div class="post-card__image-placeholder" aria-hidden="true">🚐</div>
                        <?php endif; ?>
                    </div>
                </a>
                <div class="post-card__body">
                    <div class="post-card__meta">
                        <?php echo rr_category_badge(); ?>
                        <span class="label-text"><?php echo esc_html( rr_read_time() ); ?></span>
                    </div>
                    <h3 class="post-card__title" id="related-<?php the_ID(); ?>">
                        <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
                    </h3>
                    <p class="post-card__date caption"><?php echo get_the_date(); ?></p>
                </div>
            </article>
            <?php
            endwhile;
            wp_reset_postdata();
            ?>
        </div>
    </section>
    <?php endif; ?>

    <!-- Comments -->
    <?php
    if ( comments_open() || get_comments_number() ) :
        comments_template();
    endif;
    ?>

    <!-- Hidden Pinterest image -->
    <?php if ( $hero_img ) : ?>
    <img
        src="<?php echo esc_url( $hero_img ); ?>"
        alt="<?php the_title_attribute(); ?> — Rolling Reno"
        width="735"
        height="1102"
        class="pinterest-image"
        aria-hidden="true"
    >
    <?php endif; ?>

</article>

<?php endwhile; ?>
</main>

<?php get_footer(); ?>
